language: ruby

rvm:
  - 2.4.0

before_install: gem install bundler -v 1.11.2
after_script: bundle exec rake coveralls:push

env:
  global:
    - COVERALLS_REPO_TOKEN=X5ZWSPW8VW2JXNJO0qNjlZCQNW4ju89gb
  matrix:
    - AR=4.2.10
    - AR=5.0.6
    - AR=5.1.5
    - AR=5.2.0
    - AR=5.2.5
    - AR=4.2.10 COMPAT=1
    - AR=5.0.6 COMPAT=1
    - AR=5.1.5 COMPAT=1
    - AR=5.2.0 COMPAT=1
    - AR=5.2.5 COMPAT=1
