name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Active Record v${{ matrix.activerecord }} (compat=${{ matrix.compat }})
    strategy:
      matrix:
        activerecord: ["5.2.0", "5.2.5", "6.0.4", "6.1.4"]
        compat: ["0", "1"]
        ruby: [ "2.6", "2.7"]
    env:
      AR: ${{ matrix.activerecord }}
      COMPAT: ${{ matrix.compat }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install packages
        run: sudo apt-get install libsqlite3-dev

      - name: Install bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Test
        run: bundle exec rspec
