name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Active Record v${{ matrix.activerecord }} (compat=${{ matrix.compat }})
    strategy:
      matrix:
        activerecord: ["5.2.0", "5.2.5"]
        compat: ["0", "1"]
    env:
      AR: ${{ matrix.activerecord }}
      COMPAT: ${{ matrix.compat }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install packages
        run: sudo apt-get install libsqlite3-dev

      - name: Install bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Test
        run: bundle exec rspec
